# Generated by Django 5.1.3 on 2024-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.CharField(max_length=50)),
                ('state_in_date', models.DateField()),
                ('event_code', models.CharField(max_length=20)),
                ('error_name', models.CharField(max_length=255)),
                ('error_description', models.TextField()),
            ],
        ),
    ]
