# Generated by Django 5.1.6 on 2025-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.CharField(max_length=50)),
                ('state_in_date', models.DateField(blank=True, null=True)),
                ('event_code', models.CharField(max_length=20)),
                ('error_name', models.CharField(max_length=255)),
                ('error_description', models.TextField()),
                ('recent_errors', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
