# Generated by Django 5.1.3 on 2024-11-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('top_alarms', models.IntegerField(default=0)),
                ('last_maintenance', models.DateField()),
                ('recent_errors', models.IntegerField(default=0)),
            ],
        ),
    ]
