# Generated by Django 5.1.3 on 2024-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='recent_errors',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='top_alarms',
            field=models.CharField(max_length=100),
        ),
    ]
