# Generated by Django 5.1.3 on 2024-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='state_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
