# Generated by Django 5.1.6 on 2025-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='state_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
