# Generated by Django 5.2.1 on 2025-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_state_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='report_ww',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
