# Generated by Django 5.1.3 on 2024-11-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_recent_errors_alter_tool_top_alarms'),
        ('tools', '0002_alter_tool_state_in_date'),
    ]

    operations = [
    ]
