# Generated by Django 5.2.3 on 2025-06-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tool_report_ww'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='report_ww',
        ),
    ]
