# Generated by Django 5.2.3 on 2025-06-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_tool_report_ww'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='report_ww',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
